In [1]:
import numpy as np

In [2]:
arreglo_grados = np.array([0, 30, 45, 60, 90])
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [4]:
arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [5]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [6]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [7]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [8]:
arreglo_random = np.random.randint(11)
arreglo_random

5

In [10]:
numero_random_negativo = np.random.randint(-9, 2)
numero_random_negativo

-5

In [11]:
arreglo_random = np.random.randint(10, 20, 8)
arreglo_random

array([19, 18, 14, 16, 16, 19, 10, 10])

In [12]:
np.random.rand(9)

array([0.57920581, 0.20789156, 0.33235431, 0.3886408 , 0.23906133,
       0.30639126, 0.14790825, 0.24743966, 0.53928177])

In [13]:
np.random.rand(3, 3, 2)

array([[[0.29864216, 0.46189656],
        [0.23826631, 0.58748187],
        [0.08089057, 0.819898  ]],

       [[0.83368956, 0.57518019],
        [0.61193096, 0.13810738],
        [0.46311041, 0.46400475]],

       [[0.321968  , 0.79997669],
        [0.79957189, 0.87754895],
        [0.51933484, 0.28976526]]])

In [14]:
np.average(arreglo_random)

15.25

In [15]:
np.mean(arreglo_random)

15.25

In [16]:
np.median(arreglo_random)

16.0

In [17]:
np.std(arreglo_random)

3.418698582794336

In [18]:
np.var(arreglo_random)

11.6875

In [19]:
arreglo_random.mean()

15.25